# Generated by Django 4.2 on 2023-04-11 16:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Teacher name')),
            ],
        ),
        migrations.AddField(
            model_name='mark',
            name='semester',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)], verbose_name='Semester number'),
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=6, verbose_name='Group name')),
                ('disciplines', models.ManyToManyField(to='board.discipline')),
            ],
        ),
        migrations.CreateModel(
            name='AverageMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality', models.IntegerField(default=5, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)])),
                ('methodological_support', models.IntegerField(default=5, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)])),
                ('objectivity', models.IntegerField(default=5, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)])),
                ('semester', models.IntegerField(validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)], verbose_name='Semester number')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.discipline')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.group')),
            ],
        ),
        migrations.AlterField(
            model_name='discipline',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.teacher'),
        ),
        migrations.AlterField(
            model_name='mark',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.group'),
        ),
    ]
