# Generated by Django 3.2.18 on 2023-04-11 17:26

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_teacher_mark_semester_group_averagemark_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Faculty name')),
            ],
        ),
        migrations.RemoveField(
            model_name='group',
            name='disciplines',
        ),
        migrations.AlterField(
            model_name='averagemark',
            name='semester',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)], verbose_name='Semester number'),
        ),
        migrations.AddField(
            model_name='discipline',
            name='faculty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='board.faculty'),
        ),
        migrations.AddField(
            model_name='group',
            name='faculty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='board.faculty'),
        ),
    ]
