# Generated by Django 4.2 on 2023-04-11 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_auto_20230411_2026'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupsToDiscipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.discipline')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.group')),
            ],
        ),
    ]
