# Generated by Django 3.2.18 on 2023-04-12 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_groupstodiscipline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=7, verbose_name='Group name'),
        ),
    ]
