# Generated by Django 3.2.18 on 2023-04-12 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_alter_group_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='mark',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Примітка'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Discipline name'),
        ),
    ]
